name: Build + Test + Lint

on:
  push:
    branches:
      - master
      - mamoru
  pull_request:
    branches:
      - master
      - mamoru

jobs:
  lint_test:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/lint_allowed_geth_imports.sh
        shell: bash
      - uses: actions/setup-go@v3
        with:
          go-version: '~1.20.10'
          check-latest: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: .
          args: --timeout 10m

  unit_test:
    name: Golang Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '~1.20.10'
          check-latest: true
      - run: go mod download
        shell: bash
      - run: ./scripts/build.sh ./build/subnetevm
        shell: bash
      - run: ./scripts/build_test.sh -race
        shell: bash
      - run: ./scripts/coverage.sh
        shell: bash
